using System;
using System.Collections.Generic;

namespace MumbleChatInterfacePlugin
{

    public class VoiceAttackPlugin
    {
        public static string VA_DisplayName()
        {
            return "Mumble Client Plugin";
        }

        public static string VA_DisplayInfo()
        {
            return "Sends messages to mumble chat.";  //this is just extended info that you might want to give to the user.  note that you should format this up properly.
        }

        public static Guid VA_Id()
        {
            return new Guid("{4c6f0ee1-7bc6-4da6-9adc-386b3e91df81}");  //this id must be generated by YOU... it must be unique so VoiceAttack can identify and use the plugin
        }

        public static void VA_Init1(ref Dictionary<string, object> state, ref Dictionary<string, Int16?> conditions, ref Dictionary<string, string> textValues, ref Dictionary<string, object> extendedValues)
        {
            //this is where you can set up whatever session information that you want.  this will only be called once on voiceattack load, and it is called asynchronously.
            //the state parameter is a local copy of the state held on to by VoiceAttack.  In this case, the state will be a dictionary with zero items.  You can add as many items to hold on to as you want.
            //the conditions and textValues will also be empty.  You can add whatever you want to those lists and VoiceAttack will copy the values into its own lists

            /*conditions.Add("initializedCondition1", 1);  //add some meaningless example conditions
            conditions.Add("initializedCondition2", 2);

            textValues.Add("initializedText1", "This is 1");  //add some meaningless example text values
            textValues.Add("initializedText2", "This is 2");
            
            state.Add("new state value", 369);  //add whatever private state information you want to maintain
            state.Add("second new state value", "hello");
            */


        }

        public static void VA_Invoke1(String context, ref Dictionary<string, object> state, ref Dictionary<string, Int16?> conditions, ref Dictionary<string, string> textValues, ref Dictionary<string, object> extendedValues)
        {
            //This function is where you will do all of your work.  When VoiceAttack encounters an, 'Execute External Plugin Function' action, the plugin indicated will be called.

            //What you are getting in this function as parameters :

            //context - a string that can be anything you want it to be.  this is passed in from the command action.  this was added to allow you to just pass a value into the plugin in a simple fashion (without having to set conditions/text values beforehand).  Convert the string to whatever type you need to.

            //three dictionaries which are all local copies :
            //state - all values from the state maintained by VoiceAttack for this plugin.  the state allows you to maintain kind of a, 'session' within VoiceAttack.  this value is not persisted to disk and will be erased on restart. other plugins do not have access to this state (private to the plugin)
            //conditions - the conditions that were specified in the, 'Execute External' command action.
            //textValues - the text values that were specified in the, 'Execute External' command action.
            //(you also get, 'extendedValues', but, that will be null because it is for future use)

            //the condition and text value dictionaries can be manipulated as follows :
            //items can be updated
            //items can be added to the dictionary
            //to indicate to VoiceAttack that you want to remove an item from the each dictionary, set its value to null (a process is already in place to remove items that are null for cleanup purposes, so, we can just use that)
            //any updated values will be reflected back to existing VoiceAttack internal values.
            //any added values will be added to the VoiceAttack internal values.

            //the state dictionary is the complete state.  you can manipulate it however you want, the whole thing will be copied back and replace what VoiceAttack is holding on to

            //if the, 'Execute External Plugin Function' command action has the, 'wait for return' flag set, VoiceAttack will wait until this function completes so that you may check condition values and
            //have VoiceAttack react accordingly.  otherwise, VoiceAttack fires and forgets and doesn't hang out for extra processing.


            //below is just some sample code showing how to work with dicitionaries...  in case you're not familiar with them.  just wouldn't feel complete unless i included it for some reason :)

            //here we test to see if the dictionary contains a certain key.  checking for the key first is important to avoid errors.  you can do this when setting a value and, 'TryGetValue' when you are retrieving values
            
            /*
             if (conditions.ContainsKey("someValueIWantToClear")) //looking for a condition named, 'someValueIWantToClear'
                conditions["someValueIWantToClear"] = null;  //the item was found... set it to null so it will be removed from the collection on return
            else
                conditions.Add("someValueIWantToClear", null);  //this is in case the value was not passed in, but you want to clear the value (if it exists in VoiceAttack's list) on return
            */

            /*
            //here we are adding some stuff to state
            object objValue = null;
            String strStateValue = null;
            if (state.TryGetValue("myStateValue", out objValue))  //we check to see if there is a value in state for 'myStateValue'
            {
                strStateValue = (String)objValue; //if we find something, we are going to cast it as a string and use it somewhere in here...
            }
            else
                strStateValue = "initialized";  //nothing was found in state... just set the string to, 'initialized' and keep moving...

            */
            //hope that helps some!

        }

        public static void VA_Exit1(ref Dictionary<string, object> state)
        {
            //this function gets called when VoiceAttack is closing (normally).  You would put your cleanup code in here, but be aware that your code must be robust enough to not absolutely depend on this function being called
            /*if (state.ContainsKey("myStateValue"))
            {
                //do some kind of file cleanup or whatever at this point
            }
            */
        }

    }
}